# CloudFlare Worker configuration file

name = "grok-api-proxy"
main = "grok-api-proxy.ts"
compatibility_date = "2023-12-01"

# Configure routes for your custom domain
# Uncomment and modify these lines with your actual domain
# routes = [
#   { pattern = "api-grok.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]

# This proxy doesn't require any environment variables as it simply forwards requests
# If you want to add authentication or other features, you can add environment variables here
# [vars]
# API_KEY = ""
